/** Mini-simulateurs des pages (RECETTE §9.3), en polonais et en anglais, calculés par `engine/pl.ts`. */
import { uop, uopYear, zlecenie, dzielo, b2b, b2bZusMonth, grossForNet, sickPay, overtime, capMonth, PARAMS as P } from './engine/pl';
import { formatMoney, formatNumber, pct } from './format';
import type { MiniSpec } from './mini-types';

type L = string;
const T = <A>(l: L, pl: A, en: A) => (l === 'en' ? en : pl);
const $ = (x: number, l: L) => formatMoney(x, 0, l);
const MONTHS: Record<string, string[]> = {
  pl: ['styczeń', 'luty', 'marzec', 'kwiecień', 'maj', 'czerwiec', 'lipiec', 'sierpień', 'wrzesień', 'październik', 'listopad', 'grudzień'],
  en: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
};
const month = (m: number | null, l: L) => (m ? MONTHS[l === 'en' ? 'en' : 'pl'][m - 1] : T(l, 'nie w tym roku', 'not this year'));
const gross = (l: L, def = 8000) => ({ id: 'g', label: T(l, 'Brutto miesięcznie', 'Monthly gross'), def, unit: 'zł', max: 2000000 });
const yes = (l: L, id: string, label: string, def = 0) => ({ id, label, def, options: [{ value: '0', label: T(l, 'Nie', 'No') }, { value: '1', label: T(l, 'Tak', 'Yes') }] });
const full = (l: L) => T(l, 'Pełny kalkulator wynagrodzeń', 'Full salary calculator');

const SPECS: Record<string, (l: L) => MiniSpec> = {
  minimum: (l) => ({ title: T(l, 'Ile netto na płacy minimalnej przy Twoim etacie?', 'Net minimum wage for your working time'), cta: full(l),
    inputs: [{ id: 'e', label: T(l, 'Wymiar etatu', 'Working time'), def: 100, unit: '%', max: 100 }, yes(l, 'u', T(l, 'Poniżej 26 lat?', 'Under 26?'))],
    run: ({ e, u }) => { const g = P.minimum_wage.monthly * e / 100; const m = uop({ gross: g, under26: u === 1 });
      return { head: [T(l, 'Netto miesięcznie', 'Net per month'), $(m.net, l)], rows: [[T(l, 'Brutto (płaca minimalna × etat)', 'Gross (minimum × working time)'), $(g, l)], ['ZUS', $(m.social, l)], [T(l, 'Składka zdrowotna', 'Health contribution'), $(m.health, l)], ['PIT', $(m.pit, l)]] }; } }),
  average: (l) => ({ title: T(l, 'Gdzie jest Twoja pensja wobec przeciętnej?', 'Where your pay stands against the average'), cta: full(l), inputs: [gross(l, 7000)],
    run: ({ g }) => ({ head: [T(l, 'Twoje brutto to', 'Your gross is'), `${formatNumber((g / P.average_wage.forecast_2026) * 100, 0, l)} %`], rows: [[T(l, 'Prognozowane przeciętne 2026', '2026 forecast average'), $(P.average_wage.forecast_2026, l)], [T(l, 'Twoje netto', 'Your net'), $(uop({ gross: g }).net, l)], [T(l, 'Netto przy przeciętnej', 'Net at the average'), $(uop({ gross: P.average_wage.forecast_2026 }).net, l)]] }) }),
  zus: (l) => ({ title: T(l, 'Twoje składki ZUS w 2026 r.', 'Your 2026 ZUS contributions'), cta: full(l), inputs: [gross(l)],
    run: ({ g }) => { const m = uop({ gross: g }); return { head: [T(l, 'ZUS pracownika miesięcznie', 'Employee ZUS per month'), $(m.social, l)], rows: [[T(l, 'Emerytalna', 'Pension'), $(m.emerytalna, l)], [T(l, 'Rentowa', 'Disability'), $(m.rentowa, l)], [T(l, 'Chorobowa', 'Sickness'), $(m.chorobowa, l)], [T(l, 'ZUS i fundusze po stronie pracodawcy', 'Employer ZUS and funds'), $(m.er.total, l)]] }; } }),
  health: (l) => ({ title: T(l, 'Ile wynosi Twoja składka zdrowotna?', 'How much is your health contribution?'), cta: full(l),
    inputs: [gross(l), { id: 'k', label: T(l, 'Umowa', 'Contract'), def: 0, options: [{ value: '0', label: T(l, 'Umowa o pracę', 'Employment contract') }, { value: '1', label: T(l, 'Umowa zlecenie', 'Mandate contract') }, { value: '2', label: T(l, 'B2B liniowy', 'B2B flat tax') }, { value: '3', label: T(l, 'B2B ryczałt', 'B2B lump sum') }] }],
    run: ({ g, k }) => { const h = k === 0 ? uop({ gross: g }).health : k === 1 ? zlecenie({ gross: g }).health : b2b({ revenue: g, form: k === 2 ? 'liniowy' : 'ryczalt' }).health;
      return { head: [T(l, 'Składka zdrowotna miesięcznie', 'Health contribution per month'), $(h, l)], rows: [[T(l, 'Rocznie', 'Per year'), $(h * 12, l)], [T(l, 'Udział w kwocie brutto / przychodu', 'Share of gross / revenue'), pct(g > 0 ? h / g : 0, l)]], note: k >= 2 ? T(l, 'B2B: kwota na podstawie średniego przychodu w roku, bez kosztów.', 'B2B: based on yearly average revenue, no costs.') : undefined }; } }),
  brackets: (l) => ({ title: T(l, 'Od którego miesiąca zapłacisz 32 %?', 'From which month do you pay 32 %?'), cta: full(l), inputs: [gross(l, 12000)],
    run: ({ g }) => { const y = uopYear({ gross: g }); const m = y.months.find((x) => x.secondBracket);
      return { head: [T(l, 'Drugi próg od', 'Second bracket from'), month(m ? m.month : null, l)], rows: [[T(l, 'PIT za rok', 'PIT for the year'), $(y.total.pit, l)], [T(l, 'Podstawa opodatkowania w roku', 'Taxable base for the year'), $(y.total.taxBase, l)], [T(l, 'Netto w styczniu / w grudniu', 'Net in January / December'), `${$(y.months[0].net, l)} / ${$(y.months[11].net, l)}`]] }; } }),
  allowance: (l) => ({ title: T(l, 'Ile daje kwota wolna w Twojej wypłacie?', 'What the tax-free amount is worth in your pay'), cta: full(l), inputs: [gross(l, 6000)],
    run: ({ g }) => { const a = uop({ gross: g }), b = uop({ gross: g, pit2: false });
      return { head: [T(l, 'Więcej na rękę co miesiąc z PIT-2', 'More take-home each month with PIT-2'), $(a.net - b.net, l)], rows: [[T(l, 'Zaliczka z PIT-2', 'Advance with PIT-2'), $(a.pit, l)], [T(l, 'Zaliczka bez PIT-2', 'Advance without PIT-2'), $(b.pit, l)], [T(l, 'Kwota zmniejszająca rocznie', 'Annual tax-reducing amount'), $(P.pit.tax_reducing_amount_year, l)]] }; } }),
  kup: (l) => ({ title: T(l, 'Koszty 250 zł czy 300 zł: ile zyskujesz?', '250 zł or 300 zł costs: what you gain'), cta: full(l), inputs: [gross(l, 7000)],
    run: ({ g }) => { const a = uop({ gross: g }), b = uop({ gross: g, kup: 'raised' }); const y = uopYear({ gross: g }).total.net, yb = uopYear({ gross: g, kup: 'raised' }).total.net;
      return { head: [T(l, 'Zysk rocznie przy kosztach podwyższonych', 'Yearly gain with raised costs'), $(yb - y, l)], rows: [[T(l, 'Netto z KUP 250 zł', 'Net with 250 zł costs'), $(a.net, l)], [T(l, 'Netto z KUP 300 zł', 'Net with 300 zł costs'), $(b.net, l)]] }; } }),
  youth: (l) => ({ title: T(l, 'Ile zyskujesz na uldze dla młodych?', 'What the youth relief saves you'), cta: full(l), inputs: [gross(l, 6000)],
    run: ({ g }) => { const a = uopYear({ gross: g, under26: true }), b = uopYear({ gross: g }); const last = a.months.filter((m) => m.exempt > 0).pop();
      return { head: [T(l, 'Oszczędność na PIT w roku', 'PIT saved in the year'), $(b.total.pit - a.total.pit, l)], rows: [[T(l, 'Netto miesięcznie z ulgą', 'Monthly net with the relief'), $(a.months[0].net, l)], [T(l, 'Netto bez ulgi', 'Net without the relief'), $(b.months[0].net, l)], [T(l, 'Limit 85 528 zł wyczerpany', 'Limit used up in'), a.total.exempt >= P.pit.youth_exempt_limit - 1 ? month(last ? last.month : null, l) : T(l, 'nie w tym roku', 'not this year')]] }; } }),
  cap: (l) => ({ title: T(l, 'Kiedy przestaniesz płacić emerytalną i rentową?', 'When pension and disability contributions stop'), cta: full(l), inputs: [gross(l, 25000)],
    run: ({ g }) => { const y = uopYear({ gross: g }); const m = capMonth(g);
      return { head: [T(l, 'Limit 30-krotności przekroczony w', 'Cap crossed in'), month(m, l)], rows: [[T(l, 'Limit roczny 2026', '2026 annual cap'), $(P.zus.annual_cap, l)], [T(l, 'Netto w styczniu', 'Net in January'), $(y.months[0].net, l)], [T(l, 'Netto w grudniu', 'Net in December'), $(y.months[11].net, l)]] }; } }),
  ryczalt: (l) => ({ title: T(l, 'Ile zostaje na ryczałcie?', 'What is left on the lump-sum tax'), cta: T(l, 'Pełny kalkulator B2B', 'Full B2B calculator'),
    inputs: [{ id: 'g', label: T(l, 'Przychód miesięcznie', 'Monthly revenue'), def: 15000, unit: 'zł', max: 2000000 }, { id: 'r', label: T(l, 'Stawka', 'Rate'), def: 0, options: P.b2b.ryczalt_rates.map((r, i) => ({ value: String(i), label: `${pct(r.rate, l)} · ${l === 'en' ? r.label_en : r.label_pl}` })) }],
    run: ({ g, r }) => { const x = b2b({ revenue: g, form: 'ryczalt', ryczaltRate: P.b2b.ryczalt_rates[r]?.rate ?? 0.12 });
      return { head: [T(l, 'Na rękę miesięcznie', 'Take-home per month'), $(x.net, l)], rows: [['ZUS', $(x.social + x.fp, l)], [T(l, 'Składka zdrowotna', 'Health contribution'), $(x.health, l)], [T(l, 'Ryczałt', 'Lump-sum tax'), $(x.tax, l)]] }; } }),
  liniowy: (l) => ({ title: T(l, 'Ile zostaje na podatku liniowym?', 'What is left on the flat tax'), cta: T(l, 'Pełny kalkulator B2B', 'Full B2B calculator'),
    inputs: [{ id: 'g', label: T(l, 'Przychód miesięcznie', 'Monthly revenue'), def: 20000, unit: 'zł', max: 2000000 }, { id: 'c', label: T(l, 'Koszty miesięcznie', 'Monthly costs'), def: 2000, unit: 'zł', max: 2000000 }],
    run: ({ g, c }) => { const x = b2b({ revenue: g, costs: c, form: 'liniowy' });
      return { head: [T(l, 'Na rękę miesięcznie', 'Take-home per month'), $(x.net, l)], rows: [['ZUS', $(x.social + x.fp, l)], [T(l, 'Składka zdrowotna (4,9 %)', 'Health contribution (4.9 %)').replace(/\(.*\)/, `(${pct(P.b2b.health.liniowy_rate, l)})`), $(x.health, l)], [T(l, 'Zdrowotna odliczona od dochodu', 'Health deducted from income'), $(x.healthDeducted, l)], [T(l, 'Podatek', 'Tax'), $(x.tax, l)]] }; } }),
  zusb2b: (l) => ({ title: T(l, 'Twój ZUS jako przedsiębiorca w 2026 r.', 'Your 2026 ZUS as a self-employed person'), cta: T(l, 'Pełny kalkulator B2B', 'Full B2B calculator'),
    inputs: [{ id: 'k', label: T(l, 'Rodzaj ZUS', 'ZUS type'), def: 0, options: [{ value: '0', label: T(l, 'Pełny ZUS', 'Full ZUS') }, { value: '1', label: T(l, 'Preferencyjny', 'Preferential') }, { value: '2', label: T(l, 'Ulga na start', 'Start-up relief') }] }, yes(l, 's', T(l, 'Dobrowolne chorobowe?', 'Voluntary sickness?'), 1)],
    run: ({ k, s }) => { const z = b2bZusMonth((['full', 'preferential', 'start'] as const)[k] ?? 'full', s === 1); const t = z.emerytalna + z.rentowa + z.chorobowa + z.wypadkowa + z.fp;
      return { head: [T(l, 'Składki społeczne miesięcznie', 'Social contributions per month'), formatMoney(t, 2, l)], rows: [[T(l, 'Podstawa wymiaru', 'Contribution base'), formatMoney(z.base, 2, l)], [T(l, 'Emerytalna + rentowa', 'Pension + disability'), formatMoney(z.emerytalna + z.rentowa, 2, l)], [T(l, 'Fundusz Pracy i Solidarnościowy', 'Labour and Solidarity Funds'), formatMoney(z.fp, 2, l)]], note: T(l, 'Do tego składka zdrowotna, zależna od formy opodatkowania.', 'Plus the health contribution, which depends on the tax regime.') }; } }),
  authors: (l) => ({ title: T(l, 'Ile daje 50 % kosztów autorskich?', 'What 50 % creative costs are worth'), cta: full(l), inputs: [gross(l, 12000), { id: 's', label: T(l, 'Część pensji za prawa autorskie', 'Share of pay for copyright'), def: 60, unit: '%', max: 100 }],
    run: ({ g, s }) => { const a = uopYear({ gross: g, authorsShare: s / 100 }), b = uopYear({ gross: g });
      return { head: [T(l, 'Mniej podatku w roku', 'Less tax in the year'), $(b.total.pit - a.total.pit, l)], rows: [[T(l, 'Netto miesięcznie (styczeń)', 'Net per month (January)'), $(a.months[0].net, l)], [T(l, 'Netto bez praw autorskich', 'Net without copyright'), $(b.months[0].net, l)], [T(l, 'Limit kosztów 50 % rocznie', 'Annual limit on 50 % costs'), $(P.pit.kup_authors_limit, l)]] }; } }),
  student: (l) => ({ title: T(l, 'Student na zleceniu: ile na rękę?', 'Student on zlecenie: take-home'), cta: T(l, 'Kalkulator umowy zlecenia', 'Mandate contract calculator'), inputs: [gross(l, 3500)],
    run: ({ g }) => { const a = zlecenie({ gross: g, student: true }), b = zlecenie({ gross: g, under26: true }), c = zlecenie({ gross: g });
      return { head: [T(l, 'Student do 26 lat', 'Student under 26'), $(a.net, l)], rows: [[T(l, 'Nie student, poniżej 26 lat', 'Non-student under 26'), $(b.net, l)], [T(l, 'Powyżej 26 lat', 'Over 26'), $(c.net, l)]] }; } }),
  pit2: (l) => ({ title: T(l, 'Ile tracisz bez PIT-2?', 'What you lose without PIT-2'), cta: full(l), inputs: [gross(l, 5000), { id: 'k', label: T(l, 'Umowa', 'Contract'), def: 0, options: [{ value: '0', label: T(l, 'Umowa o pracę', 'Employment contract') }, { value: '1', label: T(l, 'Umowa zlecenie', 'Mandate contract') }, { value: '2', label: T(l, 'Umowa o dzieło', 'Specific-work contract') }] }],
    run: ({ g, k }) => { const f = (p2: boolean) => (k === 0 ? uop({ gross: g, pit2: p2 }).net : k === 1 ? zlecenie({ gross: g, pit2: p2 }).net : dzielo({ gross: g, pit2: p2 }).net);
      const d = f(true) - f(false); return { head: [T(l, 'Różnica miesięcznie', 'Monthly difference'), $(d, l)], rows: [[T(l, 'Netto z PIT-2', 'Net with PIT-2'), $(f(true), l)], [T(l, 'Netto bez PIT-2', 'Net without PIT-2'), $(f(false), l)], [T(l, 'Rocznie', 'Per year'), $(d * 12, l)]] }; } }),
  zlecdzielo: (l) => ({ title: T(l, 'Zlecenie czy dzieło przy tej samej kwocie?', 'Zlecenie or dzieło for the same amount'), cta: full(l), inputs: [{ id: 'g', label: T(l, 'Kwota umowy brutto', 'Gross contract amount'), def: 4000, unit: 'zł', max: 2000000 }],
    run: ({ g }) => { const z = zlecenie({ gross: g }), d = dzielo({ gross: g });
      return { head: [T(l, 'Różnica na rękę na korzyść dzieła', 'Take-home gap in favour of dzieło'), $(d.net - z.net, l)], rows: [[T(l, 'Netto na zleceniu', 'Net on zlecenie'), $(z.net, l)], [T(l, 'Netto na dziele', 'Net on dzieło'), $(d.net, l)], [T(l, 'Składki ZUS i zdrowotna na zleceniu', 'ZUS and health on zlecenie'), $(z.social + z.health, l)]] }; } }),
  employer: (l) => ({ title: T(l, 'Ile kosztujesz pracodawcę?', 'What you cost your employer'), cta: T(l, 'Pełny kalkulator kosztu pracodawcy', 'Full employer cost calculator'), inputs: [gross(l, 8000), yes(l, 'p', T(l, 'PPK?', 'PPK?'))],
    run: ({ g, p }) => { const m = uop({ gross: g, ppk: p === 1 }); return { head: [T(l, 'Całkowity koszt miesięcznie', 'Total cost per month'), $(m.er.cost, l)], rows: [[T(l, 'Brutto', 'Gross'), $(g, l)], [T(l, 'Składki i fundusze pracodawcy', 'Employer contributions and funds'), $(m.er.total, l)], [T(l, 'Netto pracownika', 'Employee net'), $(m.net, l)]] }; } }),
  nettobrutto: (l) => ({ title: T(l, 'Jakie brutto da Ci tę kwotę na rękę?', 'What gross gives you this take-home?'), cta: T(l, 'Pełny kalkulator netto brutto', 'Full net-to-gross calculator'), inputs: [{ id: 'n', label: T(l, 'Netto miesięcznie', 'Monthly net'), def: 6000, unit: 'zł', max: 1000000 }],
    run: ({ n }) => { const g = grossForNet(n); const m = uop({ gross: g }); return { head: [T(l, 'Potrzebne brutto', 'Gross needed'), $(g, l)], rows: [['ZUS', $(m.social, l)], [T(l, 'Zdrowotna', 'Health'), $(m.health, l)], ['PIT', $(m.pit, l)]] }; } }),
  compare: (l) => ({ title: T(l, 'B2B czy etat przy tej samej kwocie?', 'B2B or employment for the same amount'), cta: T(l, 'Pełne porównanie', 'Full comparison'), inputs: [{ id: 'g', label: T(l, 'Brutto na etacie = przychód na B2B', 'Employment gross = B2B revenue'), def: 15000, unit: 'zł', max: 2000000 }],
    run: ({ g }) => ({ head: [T(l, 'Netto na umowie o pracę', 'Net on employment'), $(uop({ gross: g }).net, l)], rows: [[T(l, 'B2B liniowy', 'B2B flat tax'), $(b2b({ revenue: g, form: 'liniowy' }).net, l)], [T(l, 'B2B ryczałt 12 %', 'B2B lump sum 12 %').replace(/12 %/, pct(P.b2b.ryczalt_rates[0].rate, l)), $(b2b({ revenue: g, form: 'ryczalt', ryczaltRate: P.b2b.ryczalt_rates[0].rate }).net, l)], [T(l, 'B2B skala', 'B2B tax scale'), $(b2b({ revenue: g, form: 'skala' }).net, l)]], note: T(l, 'B2B: pełny ZUS bez chorobowego, bez kosztów firmy, bez płatnego urlopu.', 'B2B: full ZUS without sickness cover, no business costs, no paid leave.') }) }),
  annual: (l) => ({ title: T(l, 'Ile netto w skali roku?', 'Net over the whole year'), cta: T(l, 'Rok miesiąc po miesiącu', 'Year month by month'), inputs: [gross(l, 15000)],
    run: ({ g }) => { const y = uopYear({ gross: g }); const nets = y.months.map((m) => m.net);
      return { head: [T(l, 'Netto za cały rok', 'Net for the whole year'), $(y.total.net, l)], rows: [[T(l, 'Najwyższe netto w miesiącu', 'Highest monthly net'), $(Math.max(...nets), l)], [T(l, 'Najniższe netto w miesiącu', 'Lowest monthly net'), $(Math.min(...nets), l)], [T(l, 'Średnio miesięcznie', 'Monthly average'), $(y.total.net / 12, l)]] }; } }),
  hourly: (l) => ({ title: T(l, 'Stawka godzinowa na miesięczne netto', 'Hourly rate to monthly net'), cta: full(l), inputs: [{ id: 'h', label: T(l, 'Stawka brutto za godzinę', 'Gross hourly rate'), def: 40, unit: 'zł', max: 10000, decimals: 2 }, { id: 'n', label: T(l, 'Godziny w miesiącu', 'Hours per month'), def: 168, unit: 'h', max: 400 }],
    run: ({ h, n }) => { const g = h * n; const m = uop({ gross: g }); return { head: [T(l, 'Netto miesięcznie (umowa o pracę)', 'Monthly net (employment)'), $(m.net, l)], rows: [[T(l, 'Brutto miesięcznie', 'Monthly gross'), $(g, l)], [T(l, 'Netto za godzinę', 'Net per hour'), formatMoney(n > 0 ? m.net / n : 0, 2, l)], [T(l, 'Minimalna stawka godzinowa 2026', '2026 minimum hourly rate'), formatMoney(P.minimum_wage.hourly, 2, l)]] }; } }),
  overtime: (l) => ({ title: T(l, 'Ile dostaniesz za nadgodziny?', 'What overtime pays you'), cta: T(l, 'Pełny kalkulator nadgodzin', 'Full overtime calculator'), inputs: [gross(l, 7000), { id: 'o', label: T(l, 'Nadgodziny z dodatkiem 50 %', 'Overtime hours at +50 %'), def: 10, unit: 'h', max: 400 }],
    run: ({ g, o }) => { const x = overtime({ gross: g, hoursInMonth: 168, h50: o, h100: 0 }); const net = uop({ gross: g + x.extra }).net - uop({ gross: g }).net;
      return { head: [T(l, 'Dodatkowo na rękę', 'Extra take-home'), $(net, l)], rows: [[T(l, 'Brutto za nadgodziny', 'Gross for the overtime'), $(x.extra, l)], [T(l, 'Stawka godzinowa (168 h)', 'Hourly rate (168 h)'), formatMoney(x.hourly, 2, l)]] }; } }),
  sick: (l) => ({ title: T(l, 'Ile dostaniesz na L4?', 'What you get on sick leave'), cta: T(l, 'Pełny kalkulator chorobowego', 'Full sick pay calculator'), inputs: [gross(l, 7000), { id: 'd', label: T(l, 'Dni zwolnienia', 'Days of sick leave'), def: 10, unit: T(l, 'dni', 'days'), max: 182 }],
    run: ({ g, d }) => { const s = sickPay({ gross: g, days: d }); return { head: [T(l, 'Wynagrodzenie chorobowe brutto', 'Gross sick pay'), $(s.benefit, l)], rows: [[T(l, 'Za jeden dzień', 'Per day'), formatMoney(s.daily, 2, l)], [T(l, 'Pensja za te dni bez choroby', 'Normal pay for those days'), $(s.lostSalary, l)], [T(l, 'Różnica brutto', 'Gross difference'), $(s.lostSalary - s.benefit, l)]] }; } }),
  ppk: (l) => ({ title: T(l, 'Ile odkładasz w PPK i ile to kosztuje?', 'What PPK saves and what it costs'), cta: T(l, 'Pełny kalkulator PPK', 'Full PPK calculator'), inputs: [gross(l, 8000)],
    run: ({ g }) => { const a = uop({ gross: g, ppk: true }), b = uop({ gross: g }); return { head: [T(l, 'Wpłaty na Twoje konto miesięcznie', 'Paid into your account per month'), $(a.ppkEmployee + a.ppkEmployer, l)], rows: [[T(l, 'Twoja wpłata', 'Your contribution'), $(a.ppkEmployee, l)], [T(l, 'Wpłata pracodawcy', 'Employer contribution'), $(a.ppkEmployer, l)], [T(l, 'Spadek netto', 'Drop in net pay'), $(b.net - a.net, l)]] }; } }),
  bonus: (l) => ({ title: T(l, 'Ile zostanie z premii?', 'What is left of your bonus'), cta: full(l), inputs: [gross(l, 8000), { id: 'b', label: T(l, 'Premia brutto', 'Gross bonus'), def: 5000, unit: 'zł', max: 2000000 }],
    run: ({ g, b }) => { const net = uop({ gross: g + b }).net - uop({ gross: g }).net; return { head: [T(l, 'Premia na rękę', 'Bonus take-home'), $(net, l)], rows: [[T(l, 'Potrącenia z premii', 'Deductions from the bonus'), $(b - net, l)], [T(l, 'Udział potrąceń', 'Share deducted'), pct(b > 0 ? (b - net) / b : 0, l)]], note: T(l, 'Premia wypłacona w styczniu, przed drugim progiem.', 'Bonus paid in January, before the second bracket.') }; } }),
  zlecenie: (l) => ({ title: T(l, 'Zlecenie: ile na rękę?', 'Zlecenie: take-home'), cta: T(l, 'Kalkulator umowy zlecenia', 'Mandate contract calculator'), inputs: [gross(l, 4000), yes(l, 's', T(l, 'Student do 26 lat?', 'Student under 26?'))],
    run: ({ g, s }) => { const z = zlecenie({ gross: g, student: s === 1 }); return { head: [T(l, 'Netto', 'Net'), $(z.net, l)], rows: [['ZUS', $(z.social, l)], [T(l, 'Zdrowotna', 'Health'), $(z.health, l)], ['PIT', $(z.pit, l)]] }; } }),
};

export function getSpec(kind: string, lang = 'pl'): MiniSpec {
  const f = SPECS[kind]; if (!f) throw new Error(`mini-spec inconnu : ${kind}`); return f(lang);
}
export const MINI_KINDS = Object.keys(SPECS);
